import assert from 'node:assert/strict';
import { simulateWarlock } from '../src/sim/warlock.js';
const searing = { name: 'Searing Pain', school: 'Fire', specialization: 'Destruction', cast: 1.5, mana: 0, damage: 100, directDamage: 100, periodicDamage: 0, coefficient: 0, tooltip: '', conditional: true, conditions: ['demonicBrandBurst'] };
const run = (priority, build = { 'Demonic Brand': 3 }, options = { activePetId: 'imp' }, hit = 100) => simulateWarlock(priority, 35, 5000, 0, 0, build, 1, hit, 0, {}, options);
const times = result => result.castLog.filter(entry => entry.name === 'Searing Pain').map(entry => entry.time);
assert.deepEqual(times(run([searing])).slice(0, 6), [0, 11.5, 23], 'One cast followed by expiration wait, even without filler');
const filler = { ...searing, name: 'Shadow Bolt', school: 'Shadow', conditional: false, conditions: [] };
const result = run([searing, filler]);
assert.deepEqual(times(result).slice(0, 6), [0, 12, 24]);
assert.ok(result.castLog.some(entry => entry.name === 'Shadow Bolt' && entry.time >= 1.5 && entry.time < 12));
assert.equal(times(run([searing], {})).length, 0, 'Requires talent');
assert.equal(times(run([searing], { 'Demonic Brand': 3 }, {})).length, 0, 'Requires active pet');
assert.deepEqual(times(run([searing], undefined, undefined, 0)).slice(0, 6), [0, 1.5, 3, 4.5, 6, 7.5], 'Misses do not apply Brand and allow retry');
const petSpell = { ...filler, name: 'Firebolt', cast: 1, conditional: false };
const consumed = run([searing], { 'Demonic Brand': 1 }, { activePetId: 'imp', petSpell });
assert.ok(times(consumed)[1] < 11.5, 'Exhausting Brand charges also ends the wait');
console.log('Passed Searing Pain single applications, expiry wakeup, filler, prerequisites, misses, and consumed charges');
const branded = run([{ ...searing, cooldown: 60 }], { 'Demonic Brand': 3 }, { activePetId: 'imp', petSpell });
const triggers = branded.castLog.filter(entry => entry.name === 'Demonic Brand');
assert.equal(triggers.length, 6, 'Six successful pet attacks consume six stacks');
assert.deepEqual(triggers.map(entry => entry.enemyDebuffs.find(effect => effect.name === 'Demonic Brand').stacks), [6,5,4,3,2,1]);
assert.ok(triggers.every(entry => entry.damage >= 65 && entry.damage <= 68 && entry.time >= 1.5));
assert.equal(branded.events.find(event => event.name === 'Demonic Brand').damage, triggers.reduce((sum, entry) => sum + entry.damage, 0));
assert.ok(branded.effectUptimes.some(effect => effect.name === 'Demonic Brand' && effect.type === 'debuff'));
assert.ok(!branded.castLog.some(entry => entry.activeBuffs.some(effect => effect.name === 'Demonic Brand')));
assert.ok(branded.castLog.filter(entry => entry.time > triggers.at(-1).time).every(entry => !entry.enemyDebuffs.some(effect => effect.name === 'Demonic Brand')));
assert.ok(Math.abs(branded.damage - branded.castLog.reduce((sum, entry) => sum + entry.damage, 0)) < 1e-6, 'Bonus damage counted exactly once');
const melee = run([{ ...searing, cooldown: 60 }], { 'Demonic Brand': 3 }, { activePetId: 'felhunter' });
assert.ok(melee.castLog.some(entry => entry.name === 'Demonic Brand' && entry.damage > 0), 'Melee pets trigger Brand too');
console.log('Passed six-stack debuff, pet bonus damage, stack depletion, expiry, and damage accounting');
